[package]
name = "tessembly-conformance"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true
default-run = "tessembly-tck"
autobins = false

[dependencies]
serde_json.workspace = true

[[bin]]
name = "tessembly-tck"
path = "src/main.rs"

[[bin]]
name = "tessembly-document-tck"
path = "src/bin/document.rs"
