import fs from 'node:fs';
function edit(p,fn){const old=fs.readFileSync(p,'utf8');fs.writeFileSync(p,fn(old));}
edit('docs/SEMANTICS.md',s=>{
 const a=s.indexOf('```ebnf'),b=s.indexOf('```',a+3)+3;
 const grammar='```ebnf\npattern = sequence, { ";", sequence };\nsequence = item, { item };\nitem = atom, [ ":", block, [ block ] ];\nblock = ("D" | "U"), "(", or_expr, { ",", or_expr }, ")";\nor_expr = and_expr, { "|", and_expr };\nand_expr = unary, { "&", unary };\nunary = "!", unary | "(", or_expr, ")" | condition;\ncondition = group, { ("<" | ">"), group }\n          | piece, count_op, integer\n          | "IN(", integer, ",", integer, ",", or_expr, { ",", or_expr }, ")";\ngroup = selector, { selector };\nselector = piece, [ "[", positive_integer, "]" ];\ncount_op = "=" | "!=" | "<" | "<=" | ">" | ">=";\natom = piece | permutation | choice | wildcard | "{", pattern, "}";\n```\n\nF1/F2 are implemented in 0.3.x. [English help](HELP.en.md) / [한국어](HELP.ko.md).\n& and | borrow short-circuit logical AND/OR, not C bitwise operators. All syntax and ranges\nare checked before evaluation. A comma ANDs complete OR expressions. !I<T is rejected; use\n!(I<T). Repeated &&/||/==, assignment and group totals TS=1 are not supported.\nCounts are per-kind integers 0..256. IN uses inclusive one-based windows without resampling.\nkind[n] selects the nth local occurrence (1..256), not a token identity. Windows and ordinals\nn>1 are D-only; F1 is available in D and U. Invalid ranges are errors, not clipped windows.\n';
 return (s.slice(0,a)+grammar+s.slice(b)).replace('# RFC3 draft semantics and implementation scope','# RFC3 supply semantics — implemented F1/F2').replace('A cycle proves\nthat branch impossible.','A cycle proves\nthat positive conjunction impossible. OR requires every branch to be impossible. NOT and\nindependent windows do not leak edges into the outer graph.').replace('Logical-filter and richer QB/OQB extensions remain [design only](plans/FILTERS_QB_OQB.en.md), awaiting owner GO.','F1/F2 capabilities are filters.logic.v1, filters.count.v1, filters.window.v1, and\nfilters.occurrence.v1. Q1/M1/MATCH are not added. Setup goals, metrics and dataset policy\ncontracts remain outside supply. Existing reference/select records remain compatibility data.');
});
edit('docs/DOCUMENT.md',s=>s.replace('Legacy RFC2 documents require explicit migration. Rich QB/OQB and Boolean extensions are not implemented; see [review plan](plans/FILTERS_QB_OQB.en.md).','Legacy RFC2 documents require explicit migration. F1/F2 are implemented. Q1/M1/MATCH are not added. Existing reference/select records remain for compatibility, not new supply authoring.')+'\n\n## Implemented F1/F2\n\n`draw(IN(1,3,T)&I<T,T);` shares the compact filter parser. The normalized forms are\n`all`, `any`, `not`, `count`, `within`, `nth`, `before`, `present`. For example\n`before("I","T")`, `count("T",">=",2)`, `present(nth("T",2))`, and\n`within(1,3,present("T"))`. These are data calls, not execution. F2 is D-only.\n\nPredicate tag 2 stores a u32-length-prefixed TSFL v1 structural payload; old tags 0/1 remain.\nTSFL starts with ASCII TSFL and byte 1. Tags 0..6 are Present, Before, Count, All, Any, Not, In.\nCanonical ULEB values encode lengths, ordinals and bounds. Selectors carry ID and one-based\nordinal. Count operator bytes 0..5 are =, !=, <, <=, >, >=. Whole-document budgets include\nembedded patterns and all filter nodes. There is no source reparse or DNF/CNF expansion.\n');
edit('docs/WIRE.md',s=>s.replace('Each predicate ends with ULEB source span start/end. Self comparisons are retained.','Tag2: ULEB byte length followed by TSFL v1 filter bytes.\nEach predicate ends with ULEB source span start/end. Self comparisons are retained.')+'\n\n## Mandatory F1/F2 filter payload\n\nTSFL + byte 1 contains one structural filter. Tags: 0=Present(selector),\n1=Before(earlier,later), 2=Count(ID,operator-byte,count), 3=All(children), 4=Any(children),\n5=Not(child), 6=In(start,end,child). Selectors store UTF-8 ID plus one-based ordinal.\nLengths/counts use canonical ULEB; count operators 0..5 are =, !=, <, <=, >, >=.\nChild lists are nonempty/bounded, windows are inclusive/one-based. Unknown required tags fail.\nTSDC shares the payload for named IDs. Wire=1 and semantic=3 remain; old readers must reject\nnew tags, never drop filters. Current npm/Wasm assets require ABI=3.\n');
edit('docs/COMPARATOR_MIGRATION.md',s=>{
 const a=s.indexOf('## Approval boundary'),b=s.indexOf('## Sources',a);
 return (s.slice(0,a)+'## Current implementation / 현재 구현\n\nF1/F2 logic, counts, windows and ordinals are implemented in 0.3.x. The comparator migration\nstarted in 0.2.0. Current wrapper/Wasm ABI is 3 (initial RFC3-only builds used ABI 2).\nQ1/M1/MATCH and setup/policy/dataset extensions are not added. Basic reference/select records\nare retained for file compatibility.\n\nF1/F2는 0.3.x에 구현되어 있습니다. 최초 RFC3 변경은 0.2.0에서 시작했고 현재\nwrapper/Wasm ABI는 3입니다. 초기 ABI=2 자산과 혼용하지 마세요. Q1/M1/MATCH는\n추가하지 않고 기존 reference/select 레코드만 호환 목적으로 보존합니다.\n\n'+s.slice(b)).replace('Wasm ABI is now 2','The initial RFC3 Wasm ABI was 2; current F1/F2 requires ABI 3').replace('Wasm ABI는 2이므로','초기 RFC3 ABI는 2였고 현재 F1/F2 ABI는 3이므로');
});
edit('README.md',s=>{
 const a=s.indexOf('## RFC3 comparator alignment and review gate');
 s=s.slice(0,a)+'## Implemented supply filters\n\nF1/F2 are implemented. See [English help](docs/HELP.en.md), [한국어](docs/HELP.ko.md)\nand the [filters guide](https://daejunnom.github.io/Tessembly/en/filters/).\n\n```text\nP4:D(I<T&T)\nP4:D(I<T|S<Z)\nP4:D(!T)\nP4:D(T=1&S=0)\nP7:D(IN(1,3,T))\n{P7P7}:D(I[2]<T[2])\n```\n\n< means earlier; > means later. &/|/! are logical operators; comma lists mean AND.\nIN is inclusive and one-based; kind[n] is local occurrence, not token identity. F2 is D-only.\nQ1/M1/MATCH and policy/dataset expansions are not added. Existing reference/select records\nare compatibility data. Documentation examples and truth tables run against the actual CLI\nbefore Pages deploys. Authored chapter data also supplies both native help languages.\n';
 return s.replaceAll('0.2.0','0.3.0').replaceAll('comparator-alignment candidate','implemented supply-filter candidate').replace('Old RFC1 files are never inferred or silently migrated.','Old RFC2 files require explicit migration; RFC1 is not silently interpreted.').replace('Before/Present relations and local impossibility proofs','Supply filters and local impossibility proofs').replace('use, reference and select.','use; existing reference/select compatibility records remain readable.').replaceAll('cargo run --locked -p tessembly-conformance -- --report','cargo run --locked -p tessembly-conformance --bin tessembly-tck -- --report');
});
for(const lang of ['en','ko']){
 const file=lang==='en'?'packages/npm/README.md':'packages/npm/README.ko.md';
 edit(file,s=>s+'\n\n## F1/F2\n\n```text\nP4:D(I<T&T)\nP4:D(I<T|S<Z)\nP4:D(!T)\nP4:D(T=1&S=0)\nP7:D(IN(1,3,T))\n{P7P7}:D(I[2]<T[2])\n```\n\n'+(lang==='en'?'IN uses inclusive one-based bounds; kind[n] selects a local occurrence. &/| are logical. F2 is D-only. All ranges are checked before short circuit. Q1/M1/MATCH are not provided. Use wrapper/Wasm from the same ABI=3 package.':'IN은 1-based 양 끝 포함이고 미노[n]은 범위 안의 등장 차수입니다. &/|는 논리 연산입니다. F2는 D 전용이며 모든 범위는 단락 평가 전에 검사합니다. Q1/M1/MATCH는 제공하지 않습니다. wrapper/Wasm은 같은 ABI=3 패키지를 사용하세요.')+'\n');
}
edit('docs/TEST_PORT.md',s=>s+'\n\n## Optional F1/F2 suite\n\n`tessembly-filter-tck --report filters.json -- YOUR_HOST test-port` checks\nfilters.logic.v1, filters.count.v1, filters.window.v1, filters.occurrence.v1.\nIt compares exact small supplies and explicit malformed/unsupported cases through a real\nhost boundary. This is an external developer tool, not a runtime or PC certification service.\n');
fs.appendFileSync('apps/docs/tests/docs.spec.ts',`\nfor (const locale of ['en','ko'] as const) {\n  test(\`\${locale}: implemented symbols and selectors are public\`,async({page})=>{\n    await page.goto(\`/Tessembly/\${locale}/filters/\`);\n    await expect(page.locator('#logic')).toContainText('P4:D(I<T|S<Z)');\n    await expect(page.locator('#count')).toContainText('T!=0');\n    await expect(page.locator('#window')).toContainText('IN(1,3,T)');\n    await expect(page.locator('#occurrence')).toContainText('I[2]<T[2]');\n    await expect(page.locator('a[href*=review-plan]')).toHaveCount(0);\n  });\n}\n`);
