<script lang="ts">
  import { base } from '$app/paths';
  import { documentPath } from './i18n.js';
  import CodeBlock from './CodeBlock.svelte';
  export let locale: 'en'|'ko' = 'en';
  const texts={
    en:{title:'One format for piece supply',description:'Tessembly documentation: compact and advanced syntax, Rust/Wasm, binary interchange and external integration tools.',h1:'Piece supply,',h2:'in one format.',lead:'Queues and patterns. Precise order and observation contracts. Write, validate and exchange with small Rust and zero-dependency npm libraries.',start:'Get started',syntax:'Explore syntax',short:'Write less. Say exactly what you mean.',explain:'T and S before I. No ordering between T and S.',label:'Deterministic sets · no random parsing',group:'No order within the group',need:'Use only what you need.',cards:[['Familiar input, extended','Attach D/U constraints to queues and patterns. Use braces to make scope explicit.','Compact syntax'],['Structured declarations','Describe custom bags, observation, hold and references as data, not executable code.','Advanced syntax'],['Connect your program','Choose Rust crates or the npm library. External developers test their real request boundary.','Integration guide']],end:'A format, not a mandatory engine.',boundary:'Tessembly is not a PC solver or replay engine. Users and external developers own Clearra, CTK3, HF and other dataset integrations.',scope:'Read the responsibility boundaries'},
    ko:{title:'미노 공급을 위한 공통 형식',description:'테섬블리 단축·고급 문법, Rust/Wasm, 바이너리 교환과 외부 개발자용 도구 설명.',h1:'미노 공급을',h2:'하나의 형식으로.',lead:'큐와 패턴, 순서와 관측 조건을 명확하게. 작은 Rust 라이브러리와 zero-dependency npm으로 작성하고 검증하고 교환하세요.',start:'시작하기',syntax:'문법 살펴보기',short:'짧게 쓰고, 정확하게 전달합니다.',explain:'T와 S는 I보다 먼저. T와 S 사이의 순서는 자유롭게.',label:'결정론적인 공급 집합 · 난수 파싱 없음',group:'그룹 안의 순서는 무관',need:'필요한 만큼만 사용하세요.',cards:[['익숙한 입력의 확장','기존 큐·패턴에 D·U 조건을 붙입니다. 중괄호로 적용 범위를 명시합니다.','단축 문법'],['정형화된 고급 선언','커스텀 가방, 관측, 홀드, 외부 참조를 실행 코드가 아닌 데이터로 선언합니다.','고급 문법'],['자신의 프로그램과 연결','Rust 크레이트나 npm 라이브러리를 선택하고 실제 요청 경계를 시험합니다.','연동 가이드']],end:'형식을 제공하고, 실행을 강제하지 않습니다.',boundary:'테섬블리는 PC 탐색기나 리플레이 엔진이 아닙니다. Clearra·CTK3·HF 등의 연결과 데이터셋 조회는 사용자 또는 외부 개발자가 담당합니다.',scope:'프로젝트의 책임 경계 읽기'}
  };
  $: t=texts[locale];
</script>
<svelte:head><title>Tessembly — {t.title}</title><meta name="description" content={t.description} /></svelte:head>
<section class="hero"><div class="eyebrow"><span class="status-dot"></span>TETRIS SUPPLY LANGUAGE</div><h1>{t.h1}<br /><span>{t.h2}</span></h1><p class="hero-lead">{t.lead}</p><div class="hero-actions"><a class="button primary" href={documentPath(base,locale,'quickstart')}>{t.start} <span aria-hidden="true">→</span></a><a class="button secondary" href={documentPath(base,locale,'compact')}>{t.syntax}</a></div></section>
<div class="example-panel"><div><span class="eyebrow">ONE PATTERN. PRECISE MEANING.</span><h2>{t.short}</h2><p>{t.explain}</p><span class="example-label">{t.label}</span></div><div><CodeBlock text="P4:D(I<TS)" /><div class="mino-row" aria-label={t.explain}><span class="mino purple">T</span><span class="mino green">S</span><span class="mino-arrow" aria-hidden="true">→</span><span class="mino cyan">I</span><span class="mino-comment">{t.group}</span></div></div></div>
<section class="overview"><div class="section-top"><span class="eyebrow">A SMALL, COMPOSABLE FORMAT</span><h2>{t.need}</h2></div><div class="feature-grid">{#each t.cards as card,i}<a class="feature-card" href={documentPath(base,locale,['compact','advanced','integrators'][i])}><span class="card-index">0{i+1} / {['WRITE','DESCRIBE','CONNECT'][i]}</span><h3>{card[0]}</h3><p>{card[1]}</p><span class="card-link">{card[2]} →</span></a>{/each}</div></section>
<aside class="home-boundary"><span class="eyebrow">CLEAR BOUNDARIES</span><h2>{t.end}</h2><p>{t.boundary}</p><a href={documentPath(base,locale,'scope')}>{t.scope} →</a></aside>
